#!/usr/bin/env python

CELL_X = 23
CELL_Y = 23
ROOM_OFFSET = 2
ROOM_BOUND_RECT = 2
MAX_ROOM_X = 18
MAX_ROOM_Y = 18
MIN_ROOM_X = 15 # Cant be less than 2*ROOM_BOUND_RECT
MIN_ROOM_Y = 15
POINTS_PER_RECT = 3
DOOR_CHANCE = 1
SPACE = 0
WALL = 1
DOOR = 2
CORRIDOR = 3